[package]
name = "Question_2_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand_chacha = "0.3.1"
rand = "0.8.5"
rayon = "1.7.0"
indicatif = {version = "0.17.3", features = ["rayon"]}